export const GET_JOB_REQUEST = 'GET_JOB_REQUEST'
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS'
export const GET_JOB_FAILURE = 'GET_JOB_FAILURE'

export const SEARCH_JOB_REQUEST = 'SEARCH_JOB_REQUEST'
export const SEARCH_JOB_SUCCESS = 'SEARCH_JOB_SUCCESS'
export const SEARCH_JOB_FAILURE = 'SEARCH_JOB_FAILURE'

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE'

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST'
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS'
export const DELETE_JOB_FAILURE = 'DELETE_JOB_FAILURE'

export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST'
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS'
export const UPDATE_JOB_FAILURE = 'UPDATE_JOB_FAILURE'

export const CLEAR_JOB = 'CLEAR_JOB'