export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST'
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE'

export const SEARCH_STATUS_REQUEST = 'SEARCH_STATUS_REQUEST'
export const SEARCH_STATUS_SUCCESS = 'SEARCH_STATUS_SUCCESS'
export const SEARCH_STATUS_FAILURE = 'SEARCH_STATUS_FAILURE'

export const CREATE_STATUS_REQUEST = 'CREATE_STATUS_REQUEST'
export const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS'
export const CREATE_STATUS_FAILURE = 'CREATE_STATUS_FAILURE'

export const DELETE_STATUS_REQUEST = 'DELETE_STATUS_REQUEST'
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS'
export const DELETE_STATUS_FAILURE = 'DELETE_STATUS_FAILURE'

export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST'
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS'
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE'

export const CLEAR_STATUS = 'CLEAR_STATUS'